// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

export type Anchor = { "type": "textContext", lineContent: string, surroundingLines: Array<string>, contentHash: string, range: Range, lastKnownLine: number, };
