// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { AnnotationKind } from "./AnnotationKind";

export type Annotation = { id: string, kind: AnnotationKind, body: string, labels: Array<string>, author: string, isOrphaned: boolean, replyTo?: string | null, createdAt?: string | null, updatedAt?: string | null, anchor: Anchor, };
