// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxCategory } from "./InboxCategory";
import type { NotificationSettings } from "./NotificationSettings";
import type { TrackedRepo } from "./TrackedRepo";

export type AppSettings = { author: string, defaultLabels: Array<string>, ignoredFolderNames: Array<string>, diffAlgorithm: string, defaultCheckoutRoot: string | null, trackedGithubRepos: Array<TrackedRepo>, notifications: NotificationSettings, inboxCategories: Array<InboxCategory>, inboxExcludedOrgs: Array<string>, inboxExcludedRepos: Array<string>, };
