// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { author: string, defaultLabels: Array<string>, ignoredFolderNames: Array<string>, };
