// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckRun } from "./CheckRun";

export type CheckRunsResult = { checkRuns: Array<CheckRun>, totalCount: number, passed: number, failed: number, pending: number, };
