// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckRun = { id: number, name: string, status: string, conclusion: string | null, startedAt: string | null, completedAt: string | null, detailsUrl: string | null, htmlUrl: string | null, };
