// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationKind } from "../../../../src/lib/bindings/AnnotationKind";

export type CreateAnnotationRequest = { filePath: string, body: string, labels: Array<string>, kind: AnnotationKind, startLine: number, startColumn: number, endLine: number, endColumn: number, replyTo: string | null, };
