// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type DiffResult = { baseRef: string, targetRef: string, hunks: Array<DiffHunk>, insertedLines: Array<number>, deletedLines: Array<number>, };
