// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

export type DiffChange = { kind: ChangeKind, oldLine: number | null, newLine: number | null, content: string, };
