// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffChange } from "./DiffChange";

export type DiffHunk = { oldStart: number, oldCount: number, newStart: number, newCount: number, changes: Array<DiffChange>, };
