// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";

export type FileAnnotations = { filePath: string, fileName: string, annotations: Array<Annotation>, };
