// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubSyncState } from "./GitHubSyncState";

export type GitHubAnnotationMetadata = { syncState?: GitHubSyncState | null, externalCommentId?: string | null, externalThreadId?: string | null, publishableReason?: string | null, };
