// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHubReviewQueueItem = { repo: string, number: number, title: string, url: string, author: string, updatedAt: string, baseRef: string, headRef: string, localPath: string, };
