// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubSyncState } from "./GitHubSyncState";

export type GitHubAnnotationMetadata = { syncState?: GitHubSyncState | null, 
/**
 * GraphQL node id (e.g. `PRRC_kwDOXxxx`). Used for GraphQL operations
 * like `resolveReviewThread` and as the cross-reference between
 * `reply_to` chains in imported data.
 */
externalCommentId?: string | null, 
/**
 * REST `databaseId` (e.g. `1729384756`). Required for REST endpoints
 * like `POST /pulls/comments/{id}/replies`. Populated by the import
 * path; older sidecars may have only `external_comment_id` set.
 */
externalCommentDatabaseId?: bigint | null, externalThreadId?: string | null, publishableReason?: string | null, 
/**
 * Set to `Some(true)` when the user (or an agent) flips `resolved`
 * on an annotation that was already imported (`sync_state = Imported`).
 * Triggers a `resolveReviewThread` GraphQL mutation on submit.
 */
pendingResolutionChange?: boolean | null, };
