// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHubPrSession = { id: string, repo: string, number: number, title: string, authorLogin: string, viewerLogin: string, body: string, url: string, baseRef: string, baseSha: string, headRef: string, headSha: string, localRepoPath: string, worktreePath: string, changedFiles: Array<string>, updatedAt: string, };
