// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxCategory } from "./InboxCategory";

export type GitHubInboxItem = { repo: string, number: number, title: string, url: string, author: string, updatedAt: string, categories: Array<InboxCategory>, };
