// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubPrSession } from "./GitHubPrSession";

export type ResumeReviewSessionResult = { kind: string, sessionId: string, projectRoot: string | null, files: Array<string>, githubSession: GitHubPrSession | null, };
