// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewHistoryItem = { id: string, kind: string, status: string, title: string, subtitle: string, updatedAt: string, primaryFilePath: string | null, fileCount: number, verdict: string | null, };
