// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewHistoryItem } from "./ReviewHistoryItem";

export type ReviewHistory = { activeSession: ReviewHistoryItem | null, recentPullRequests: Array<ReviewHistoryItem>, recentFiles: Array<ReviewHistoryItem>, staleSessions: Array<ReviewHistoryItem>, workspaceLocal: Array<ReviewHistoryItem>, };
