// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitSnapshot } from "./GitSnapshot";

export type SessionFile = { version: number, sessionId: string, createdAt: string, verdict?: string | null, git?: GitSnapshot | null, files: Record<string, SessionFileEntry>, };
