// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateSettingsRequest = { author: string | null, defaultLabels: Array<string> | null, ignoredFolderNames: Array<string> | null, };
