// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationSettings } from "./NotificationSettings";
import type { TrackedRepo } from "./TrackedRepo";

export type UpdateSettingsRequest = { author: string | null, defaultLabels: Array<string> | null, ignoredFolderNames: Array<string> | null, diffAlgorithm: string | null, defaultCheckoutRoot: string | null, trackedGithubRepos: Array<TrackedRepo> | null, notifications: NotificationSettings | null, };
