// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceFileMatch } from "./WorkspaceFileMatch";
import type { WorkspaceIndexStatus } from "./WorkspaceIndexStatus";

export type WorkspaceFileQueryResponse = { results: Array<WorkspaceFileMatch>, statuses: Array<WorkspaceIndexStatus>, };
