// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceIndexState } from "./WorkspaceIndexState";

export type WorkspaceIndexStatus = { root: string, state: WorkspaceIndexState, indexedCount: number, truncated: boolean, lastUpdated: string | null, error: string | null, };
